In [1]:
import numpy as np

## Datatype and attribute

In [2]:
#NumPy's main data type is ndarray- non-dimensional array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a1.shape

(3,)

In [5]:
a1.dtype

dtype('int32')

In [6]:
a1.size

3

In [7]:
import pandas as pd
df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

In [8]:
random_array = np.arange(0, 10, 2)
random_array

array([0, 2, 4, 6, 8])

In [9]:
random_array.size

5

In [10]:
random_array = np.random.randint(0, 10, size =( 3,5))

In [11]:
random_array

array([[2, 3, 1, 6, 8],
       [4, 2, 5, 7, 6],
       [9, 8, 4, 8, 8]])

In [12]:
random_array.size

15

In [13]:
high_var_array = np.array([1, 100, 200, 300, 1000, 5000])
low_val_array = np.array([2, 4, 6, 8, 10])

In [15]:
np.var(high_var_array), np.var(low_val_array)

(3146300.1388888885, 8.0)